### ISSUE TITLE
data-overflow in Mobile-view

### ISSUE THREAD

**Issue by JasonDsouza212** [AwesomeDevin/zustand-vue#1]
### The description of ZUSTAND on the **main page** overflows in the **mobile view**
![Screenshot from 2023-02-09 10-15-49](https://user-images.githubusercontent.com/74404894/217721039-3f71e8aa-3224-4709-86e3-950c48ffa66f.png)

**Comment by AwesomeDevin** [comment]
Thank you for your suggestion. I'll fix and take it
