### ISSUE TITLE
Difference between vue-zustand?

### ISSUE THREAD

**Issue by targetlucked69** [AwesomeDevin/zustand-vue#4]
Any difference between this package and [vue-zustand](https://github.com/wobsoriano/vue-zustand)? Planning to use it in a project.

**Comment by AwesomeDevin** [comment]
I have tried [vue-zustand](https://github.com/wobsoriano/vue-zustand) ,But this way of writing will not work:

![image](https://github.com/AwesomeDevin/zustand-vue/assets/22369504/eac0ea19-7f00-4118-bf4d-50f3585cd7d4)

[zustand-vue](https://github.com/AwesomeDevin/zustand-vue) can work normally, maybe the usage of `zustand-vue` will be more free in the way of writing?

[Online Demo](https://codesandbox.io/s/zustand-vue3-demo-forked-ly22ks?file=/src/components/Form.vue)

Of course, [zustand-vue](https://github.com/AwesomeDevin/zustand-vue)  may also have some unknown problems, if you find something, please let me know, thanks.
